name = "backend"
compatibility_date = "2024-07-15"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYTg3NWM4ZDEtMzMyMy00NDE1LWJkODMtZjcyM2Q2MmZiZGNjIiwidGVuYW50X2lkIjoiYzgwZGI2Mzg3OTY5NzJkNjQ5ZmEwNThhMzZiZmQzZGZmMTBlN2E3OTVhNWQxNDc3ZGE1ZjlhZGQ0Y2I3OWFkNCIsImludGVybmFsX3NlY3JldCI6IjdiOGJmYjZhLTQxM2UtNDgxNS04MmNiLTkxZDBiNjAxMDBkMCJ9.T6nITj-feJzFtFq4eL3Wr3V_yOI0c4bk6tytzTjdz-c"
JWT_SECRET= "491b644265260f59b48a1b621170cb18458f8232200110088f0bc57e78514bde"
HF_API_TOKEN="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"
